### ISSUE TITLE
The tool crashes if testcase file has been already downloaded

### ISSUE THREAD

**Issue by Dor1s** [google/clusterfuzz-tools#129]
```bash
$ clusterfuzz reproduce -dg 6083453533814784
Reproducing testcase 6083453533814784
Downloading testcase information...

We need to authenticate you in order to get information from ClusterFuzz.

Open: <....>

Please login on the opened webpage and enter your verification code: <...>
Downloading testcase data...

Detailed logs of this run can be found in: ~/.clusterfuzz/logs.
Traceback (most recent call last):
  File "/usr/local/bin/clusterfuzz", line 11, in <module>
    sys.exit(execute())
  File "/usr/local/lib/python2.7/dist-packages/clusterfuzz/main.py", line 53, in execute
    command.execute(**arg_dict)
  File "/usr/local/lib/python2.7/dist-packages/clusterfuzz/stackdriver_logging.py", line 123, in wrapped
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/clusterfuzz/commands/reproduce.py", line 250, in execute
    definition.sanitizer)
  File "/usr/local/lib/python2.7/dist-packages/clusterfuzz/reproducers.py", line 46, in __init__
    self.testcase_path = testcase.get_testcase_path()
  File "/usr/local/lib/python2.7/dist-packages/clusterfuzz/testcase.py", line 116, in get_testcase_path
    os.makedirs(testcase_dir)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/usr/local/google/home/mmoroz/.clusterfuzz/testcases/6083453533814784_testcase'
```

Once again:
```bash
$ clusterfuzz reproduce -dg 6083453533814784
Reproducing testcase 6083453533814784
Downloading testcase information...
Downloading testcase data...

Detailed logs of this run can be found in: ~/.clusterfuzz/logs.
Traceback (most recent call last):
  File "/usr/local/bin/clusterfuzz", line 11, in <module>
    sys.exit(execute())
  File "/usr/local/lib/python2.7/dist-packages/clusterfuzz/main.py", line 53, in execute
    command.execute(**arg_dict)
  File "/usr/local/lib/python2.7/dist-packages/clusterfuzz/stackdriver_logging.py", line 123, in wrapped
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/clusterfuzz/commands/reproduce.py", line 250, in execute
    definition.sanitizer)
  File "/usr/local/lib/python2.7/dist-packages/clusterfuzz/reproducers.py", line 46, in __init__
    self.testcase_path = testcase.get_testcase_path()
  File "/usr/local/lib/python2.7/dist-packages/clusterfuzz/testcase.py", line 116, in get_testcase_path
    os.makedirs(testcase_dir)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/usr/local/google/home/mmoroz/.clusterfuzz/testcases/6083453533814784_testcase'
```

**Comment by everestmz** [comment]
We introduced a change to support zipfile testcases, which has been known to create an issue if you have a file downloaded from before the update. Can you delete your testcase directory and see if this changes anything? 

If the crash still occurs when the new testcase is downloaded, I'll look into this more.

**Comment by Dor1s** [comment]
Ok, got it! `rm -rf /usr/local/google/home/mmoroz/.clusterfuzz/testcases/` helped, let's close this. Thanks!

**Comment by inferno-chromium** [comment]
Can the tool just delete existing testcase directory ? What if someone did a redo->minimize, we should clean existing testcase directory before use.

**Comment by everestmz** [comment]
So you think that re-downloading the testcase each time would be more beneficial, if it helps to avoid this?

**Comment by inferno-chromium** [comment]
Yes, since minimized testcase can change after redo. and it is a small file anyway.

**Comment by everestmz** [comment]
Ok, will add this functionality
