### ISSUE TITLE
`sudo pip install -U clusterfuzz` causes an error `TypeError: __call__() takes exactly 2 arguments (1 given)`

### ISSUE THREAD

**Issue by tanin47** [google/clusterfuzz-tools#149]
```
$  sudo pip install -U clusterfuzz
Traceback (most recent call last):
  File "/usr/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 72, in <module>
    import packaging.requirements
  File "/usr/local/lib/python2.7/dist-packages/packaging/requirements.py", line 59, in <module>
    MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
TypeError: __call__() takes exactly 2 arguments (1 given)
```

User mentioned there was a lot of output before the trace. However, after seeing this, `sudo pip` is completely broken.

It's possible that one of the dependencies (e.g. `setuptools`) breaks python. I've encountered this problem before and fixed it with https://twitter.com/tanin/status/848063975640059904

**Comment by tanin47** [comment]
We've found a way to bypass this exception. We can run: `sudo python -m pip install -U pip` instead.

**Comment by tanin47** [comment]
Ok, I think I understand the problem. Here's what user might do: `sudo pip install clusterfuzz`.

Because pip is of the version 1.5.4, this creates a few problems:
1. The user might see the stacktrace above.
2. The user might see the stacktrace in #144.
3. `appdirs` is not installed correctly. This is due to pip 1.5.4 bug, I believe.

The steps to fix this are:
1. `sudo python -m pip install -U pip` to install pip 9.0.1 in `/usr/local/bin/pip`.
2. `sudo python -m pip uninstall clusterfuzz` to uninstall broken clusterfuzz.
3. `sudo /usr/local/bin/pip install clusterfuzz` to install clusterfuzz.
4. `sudo /usr/local/bin/pip install appdirs` to install the missing appdirs.

Then, it should work.
