### ISSUE TITLE
build/install-build-deps.sh asks to accept EULA agreement even with the --no-prompt option enabled.

### ISSUE THREAD

**Issue by tanin47** [google/clusterfuzz-tools#267]
It seems we need to change the way we setup Chrome. We might want to just use an image.

**Comment by inferno-chromium** [comment]
can we get a fix in install-build-deps.sh, maybe the dev forgot to check --no-prompt option.

**Comment by inferno-chromium** [comment]
I don't see EULA with --no-prompt on chromium trunk, where do you see this ?

**Comment by tanin47** [comment]
On the CI, I'll try it again.

**Comment by tanin47** [comment]
Now it fails with:

```
2017-05-19_16:49:41.53962 sudo: no tty present and no askpass program specified
2017-05-19_16:49:41.54027 Traceback (most recent call last):
2017-05-19_16:49:41.54028   File "/python-daemon/daemon/main.py", line 202, in <module>
2017-05-19_16:49:41.54033     main()
2017-05-19_16:49:41.54034   File "/python-daemon/daemon/main.py", line 188, in main
2017-05-19_16:49:41.54037     clone_chromium.clone_chromium()
2017-05-19_16:49:41.54038   File "/python-daemon/daemon/clone_chromium.py", line 27, in clone_chromium
2017-05-19_16:49:41.54039     cwd=CHROMIUM_SRC, shell=True)
2017-05-19_16:49:41.54040   File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
2017-05-19_16:49:41.54047     raise CalledProcessError(retcode, cmd)
2017-05-19_16:49:41.54048 subprocess.CalledProcessError: Command 'sudo build/install-build-deps.sh --no-prompt' returned non-zero exit status 1
```

This is run with sudo. I think we might approach this a wrong way. It might be better to just create an image with chromium already installed. It'll be faster to spawn a CI instance as well.

**Comment by tanin47** [comment]
Ok, I just got the EULA agreement with:

```
TrueType core fonts for the Web EULA                                                                                                                                                                                                               
 │                                                                                                                                                                                                                                                    
 │ END-USER LICENSE AGREEMENT FOR MICROSOFT SOFTWARE       
...
```

I ran `sudo build/install-build-deps.sh --no-prompt` manually.

**Comment by inferno-chromium** [comment]
Actually yes, on CI, install-build-deps.sh could just mock out. We can have everything installed there, both 64-bit and 32-bit libs.

**Comment by tanin47** [comment]
This can be solved with https://github.com/google/clusterfuzz-tools/pull/271/files#diff-e3ee0d5d58665dd940349b929cc56be2R118

We are also switching to create an image beforehand.
