### ISSUE TITLE
Retrying doesn't exactly work

### ISSUE THREAD

**Issue by tanin47** [google/clusterfuzz-tools#296]
```
CI unsuccessfully finished running reproduce with testcase=[redacted], build_type=chromium, current=False, and goma=enabled
Traceback (most recent call last):
  File "/home/clusterfuzz/.pex/code/f1069284003d1cb3f3c47f632ed31bebedfb3b2b/clusterfuzz/stackdriver_logging.py", line 120, in wrapped
    func(**params)
  File "/home/clusterfuzz/.pex/code/f1069284003d1cb3f3c47f632ed31bebedfb3b2b/clusterfuzz/commands/reproduce.py", line 239, in execute
    response = get_testcase_info(testcase_id)
  File "/home/clusterfuzz/.pex/code/f1069284003d1cb3f3c47f632ed31bebedfb3b2b/clusterfuzz/commands/reproduce.py", line 115, in get_testcase_info
    return json.loads(send_request(CLUSTERFUZZ_TESTCASE_INFO_URL, data).text)
  File "/home/clusterfuzz/.pex/code/f1069284003d1cb3f3c47f632ed31bebedfb3b2b/clusterfuzz/commands/reproduce.py", line 102, in send_request
    raise common.ClusterfuzzAuthError(response.text)
ClusterfuzzAuthError: Error authenticating with Clusterfuzz

<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>500 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered an error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>
```

This happened during a deployment.

**Comment by tanin47** [comment]
This impacts the success rate of the CI. I shall fix it.
