### ISSUE TITLE
Sanity check for linux_cfi_chrome fails

### ISSUE THREAD

**Issue by tanin47** [google/clusterfuzz-tools#309]
```
Running: gclient sync
.

src/third_party/skia (ERROR)
----------------------------------------
[0:00:03] Started.
[0:00:07] From https://skia.googlesource.com/skia
[0:00:07]    c2b5175e99..6867eee44d  master     -> origin/master
_____ src/third_party/skia at 2c49a4185865140827ac4630e6b63cd03e0ad3bb
----------------------------------------
Traceback (most recent call last):
  File "/usr/local/google/home/tanin/projects/depot_tools/gclient.py", line 2298, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/google/home/tanin/projects/depot_tools/gclient.py", line 2284, in main
    return dispatcher.execute(OptionParser(), argv)
  File "/usr/local/google/home/tanin/projects/depot_tools/subcommand.py", line 252, in execute
    return command(parser, args[1:])
  File "/usr/local/google/home/tanin/projects/depot_tools/gclient.py", line 2033, in CMDsync
    ret = client.RunOnDeps('update', args)
  File "/usr/local/google/home/tanin/projects/depot_tools/gclient.py", line 1343, in RunOnDeps
    work_queue.flush(revision_overrides, command, args, options=self._options)
  File "/usr/local/google/home/tanin/projects/depot_tools/gclient_utils.py", line 1047, in run
    self.item.run(*self.args, **self.kwargs)
  File "/usr/local/google/home/tanin/projects/depot_tools/gclient.py", line 769, in run
    self.ParseDepsFile()
  File "/usr/local/google/home/tanin/projects/depot_tools/gclient.py", line 559, in ParseDepsFile
    gclient_eval.Exec(deps_content, global_scope, local_scope, filepath)
  File "/usr/local/google/home/tanin/projects/depot_tools/gclient_eval.py", line 189, in Exec
    _visit_in_module(stmt)
  File "/usr/local/google/home/tanin/projects/depot_tools/gclient_eval.py", line 185, in _visit_in_module
    getattr(node, 'lineno', '<unknown>')))
ValueError: unexpected AST node: <_ast.Import object at 0x7f55693ee390> Import(names=[alias(name='os', asname=None)]) (file '/usr/local/google/home/tanin/projects/chromium/src/third_party/skia/DEPS',line 50)
```

It comes from this line `import os` ( https://skia.googlesource.com/skia/+/2c49a4185865140827ac4630e6b63cd03e0ad3bb/DEPS#50).

Maybe the testcase is too old now. I'll switch to a newer one.

**Comment by tanin47** [comment]
Changed to #311
