### ISSUE TITLE
CI error on `gclient sync`

### ISSUE THREAD

**Issue by tanin47** [google/clusterfuzz-tools#426]
```
2017-07-20_20:34:51.18723 Running:
2017-07-20_20:34:51.18725   cmd: PATH="/usr/local/bin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bin:/home/clusterfuzz/depot_tools" gclient sync --reset
2017-07-20_20:34:51.18726   cwd: /home/clusterfuzz/chromium/src
2017-07-20_20:34:58.79479 
2017-07-20_20:34:58.79481 src/third_party/skia (ERROR)
2017-07-20_20:34:58.79483 ----------------------------------------
2017-07-20_20:34:58.79484 [0:00:00] Started.
2017-07-20_20:34:58.79484 [0:00:05] Up-to-date; skipping checkout.
2017-07-20_20:34:58.79484 _____ src/third_party/skia at ae9718f1d40556ed5a49e616dbe54087f4d0d546
2017-07-20_20:34:58.79484 ----------------------------------------
2017-07-20_20:34:58.79493 Traceback (most recent call last):
2017-07-20_20:34:58.79494   File "/home/clusterfuzz/depot_tools/gclient.py", line 2523, in <module>
2017-07-20_20:34:58.79529     sys.exit(main(sys.argv[1:]))
2017-07-20_20:34:58.79530   File "/home/clusterfuzz/depot_tools/gclient.py", line 2509, in main
2017-07-20_20:34:58.79562     return dispatcher.execute(OptionParser(), argv)
2017-07-20_20:34:58.79563   File "/home/clusterfuzz/depot_tools/subcommand.py", line 252, in execute
2017-07-20_20:34:58.79567     return command(parser, args[1:])
2017-07-20_20:34:58.79568   File "/home/clusterfuzz/depot_tools/gclient.py", line 2270, in CMDsync
2017-07-20_20:34:58.79595     ret = client.RunOnDeps('update', args)
2017-07-20_20:34:58.79596   File "/home/clusterfuzz/depot_tools/gclient.py", line 1464, in RunOnDeps
2017-07-20_20:34:58.79613     work_queue.flush(revision_overrides, command, args, options=self._options)
2017-07-20_20:34:58.79614   File "/home/clusterfuzz/depot_tools/gclient_utils.py", line 1050, in run
2017-07-20_20:34:58.79626     self.item.run(*self.args, **self.kwargs)
2017-07-20_20:34:58.79626   File "/home/clusterfuzz/depot_tools/gclient.py", line 902, in run
2017-07-20_20:34:58.79637     self.ParseDepsFile()
2017-07-20_20:34:58.79638   File "/home/clusterfuzz/depot_tools/gclient.py", line 700, in ParseDepsFile
2017-07-20_20:34:58.79647     gclient_eval.Exec(deps_content, global_scope, local_scope, filepath)
2017-07-20_20:34:58.79649   File "/home/clusterfuzz/depot_tools/gclient_eval.py", line 209, in Exec
2017-07-20_20:34:58.79651     _visit_in_module(stmt)
2017-07-20_20:34:58.79652   File "/home/clusterfuzz/depot_tools/gclient_eval.py", line 205, in _visit_in_module
2017-07-20_20:34:58.79655     getattr(node, 'lineno', '<unknown>')))
2017-07-20_20:34:58.79656 ValueError: unexpected AST node: <_ast.Import object at 0x7f74b0571c10> Import(names=[alias(name='os', asname=None)]) (file '/home/clusterfuzz/chromium/src/third_party/skia/DEPS', line 53)
```

It seems the DEPS file has a syntax error. The error is getting more and more creative.

**Comment by tanin47** [comment]
I think the exception occurs because `gclient sync` is updated. There might be some changes in syntax rules. But the DEPS in Skia is from March 2017. 

We simply just need to switch to `origin/master` before running `gclient sync --reset`.

**Comment by tanin47** [comment]
#427 fixes this problem.
