### ISSUE TITLE
Handle old testcases

### ISSUE THREAD

**Issue by tanin47** [google/clusterfuzz-tools#435]
Because old testcases cause problem with gclient. However, these old testcases still occur in recent revisions. The exception is:

```
2017-07-30 15:08:42,764 [INFO]: Running: gclient sync
2017-07-30 15:08:42,767 [DEBUG]: ---------------------------------------
2017-07-30 15:08:57,939 [DEBUG]: Killing pid=16526 with 15
2017-07-30 15:08:57,939 [DEBUG]: 
2017-07-30 15:08:57,939 [DEBUG]: src/third_party/skia (ERROR)
2017-07-30 15:08:57,939 [DEBUG]: ----------------------------------------
2017-07-30 15:08:57,939 [DEBUG]: [0:00:00] Started.
2017-07-30 15:08:57,939 [DEBUG]: _____ src/third_party/skia at ae9718f1d40556ed5a49e616dbe54087f4d0d546
2017-07-30 15:08:57,939 [DEBUG]: ----------------------------------------
2017-07-30 15:08:57,939 [DEBUG]: Traceback (most recent call last):
2017-07-30 15:08:57,940 [DEBUG]:   File "/home/clusterfuzz/depot_tools/gclient.py", line 2495, in <module>
2017-07-30 15:08:57,940 [DEBUG]:     sys.exit(main(sys.argv[1:]))
2017-07-30 15:08:57,940 [DEBUG]:   File "/home/clusterfuzz/depot_tools/gclient.py", line 2481, in main
2017-07-30 15:08:57,940 [DEBUG]:     return dispatcher.execute(OptionParser(), argv)
2017-07-30 15:08:57,940 [DEBUG]:   File "/home/clusterfuzz/depot_tools/subcommand.py", line 252, in execute
2017-07-30 15:08:57,940 [DEBUG]:     return command(parser, args[1:])
2017-07-30 15:08:57,940 [DEBUG]:   File "/home/clusterfuzz/depot_tools/gclient.py", line 2242, in CMDsync
2017-07-30 15:08:57,940 [DEBUG]:     ret = client.RunOnDeps('update', args)
2017-07-30 15:08:57,940 [DEBUG]:   File "/home/clusterfuzz/depot_tools/gclient.py", line 1431, in RunOnDeps
2017-07-30 15:08:57,940 [DEBUG]:     work_queue.flush(revision_overrides, command, args, options=self._options)
2017-07-30 15:08:57,940 [DEBUG]:   File "/home/clusterfuzz/depot_tools/gclient_utils.py", line 1050, in run
2017-07-30 15:08:57,940 [DEBUG]:     self.item.run(*self.args, **self.kwargs)
2017-07-30 15:08:57,940 [DEBUG]:   File "/home/clusterfuzz/depot_tools/gclient.py", line 884, in run
2017-07-30 15:08:57,940 [DEBUG]:     self.ParseDepsFile()
2017-07-30 15:08:57,941 [DEBUG]:   File "/home/clusterfuzz/depot_tools/gclient.py", line 689, in ParseDepsFile
2017-07-30 15:08:57,941 [DEBUG]:     gclient_eval.Exec(deps_content, global_scope, local_scope, filepath)
2017-07-30 15:08:57,941 [DEBUG]:   File "/home/clusterfuzz/depot_tools/gclient_eval.py", line 209, in Exec
2017-07-30 15:08:57,941 [DEBUG]:     _visit_in_module(stmt)
2017-07-30 15:08:57,941 [DEBUG]:   File "/home/clusterfuzz/depot_tools/gclient_eval.py", line 205, in _visit_in_module
2017-07-30 15:08:57,941 [DEBUG]:     getattr(node, 'lineno', '<unknown>')))
2017-07-30 15:08:57,941 [DEBUG]: ValueError: unexpected AST node: <_ast.Import object at 0x7f0eb45643d0> Import(names=[alias(name='os', asname=None)]) (file '/home/clusterfuzz/chromium/src/third_party/skia/DEPS', line 53)
2017-07-30 15:08:57,941 [DEBUG]: ---------------------------------------
2017-07-30 15:08:57,941 [DEBUG]: | Return code is non-zero (1).
2017-07-30 15:08:57,941 [DEBUG]: | Exit.
```

In any case, these testcases are so old that there are no gn args in its testcase detail as well.

Examples are: 5755582448664576, 6000063496323072, 5986200012980224, and 4949488323264512. There are fewer than 20 testcases. They fail on CI with CommandFailedError.

Another fix is to re-upload these testcases and close them. I might do that.

**Comment by tanin47** [comment]
This is resolved in https://bugs.chromium.org/p/chromium/issues/detail?id=750508.

We will keep doing this for older testcases until all of them are gone.
