### ISSUE TITLE
5257387891228672 fails because it requires a layout test

### ISSUE THREAD

**Issue by tanin47** [google/clusterfuzz-tools#440]
Somehow the testcase file doesn't exist:

```
Traceback (most recent call last):
  File "/usr/local/google/home/[redacted]/.pex/code/1c17e1679d8059810cdccfff4d958e8684deb0a7/clusterfuzz/stackdriver_logging.py", line 127, in wrapped
    func(**params)
  File "/usr/local/google/home/[redacted]/.pex/code/1c17e1679d8059810cdccfff4d958e8684deb0a7/clusterfuzz/commands/reproduce.py", line 269, in execute
    reproducer.reproduce(iterations)
  File "/usr/local/google/home/[redacted]/.pex/code/1c17e1679d8059810cdccfff4d958e8684deb0a7/clusterfuzz/reproducers.py", line 356, in reproduce
    self.pre_build_steps()
  File "/usr/local/google/home/[redacted]/.pex/code/1c17e1679d8059810cdccfff4d958e8684deb0a7/clusterfuzz/reproducers.py", line 492, in pre_build_steps
    self.testcase_path, self.original_testcase_path, self.source_directory)
  File "/usr/local/google/home/[redacted]/.pex/code/1c17e1679d8059810cdccfff4d958e8684deb0a7/clusterfuzz/reproducers.py", line 152, in update_testcase_path_in_layout_test
    shutil.move(testcase_path, new_testcase_path)
  File "/usr/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/usr/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: u'/usr/local/google/code/chromium/src/third_party/WebKit/LayoutTests/inspector/dom/fuzz-791-shadowRootType.html'
```

I'll investigate

**Comment by tanin47** [comment]
This testcase fails consistently on CI as well.

**Comment by tanin47** [comment]
Nevermind, we cannot fix this. The root cause is that: `/usr/local/google/code/chromium/src/third_party/WebKit/LayoutTests/inspector/dom` on the chromium's src doesn't exist.

In any case, our fix on the layout test will bypass this issue.
