### ISSUE TITLE
6154608304193536 has an issue on CI

### ISSUE THREAD

**Issue by tanin47** [google/clusterfuzz-tools#460]
We've seen this error on the CI:

`1.7.0 (release) failed to reproduce 6154608304193536 (linux_ubsan_vptr_content_shell_drt, UnknownExitCodeError, --current --skip-deps)`

The error only occurs when using `--current --skip-deps`.

Interestingly, the usage log showed:

```
clusterfuzz unsuccessfully finished (reproduce, 6154608304193536, True). 
Traceback (most recent call last): 
File "/home/clusterfuzz/.pex/code/9dafff429e765f3d21fa0585764f73aee85f8267/clusterfuzz/stackdriver_logging.py", line 125, in wrapped func(**params) 
File "/home/clusterfuzz/.pex/code/9dafff429e765f3d21fa0585764f73aee85f8267/clusterfuzz/commands/reproduce.py", line 269, in execute current_testcase.get_testcase_path() 
File "/home/clusterfuzz/.pex/code/9dafff429e765f3d21fa0585764f73aee85f8267/clusterfuzz/common.py", line 99, in wrapper result = func(*args, **kwargs) 
File "/home/clusterfuzz/.pex/code/9dafff429e765f3d21fa0585764f73aee85f8267/clusterfuzz/testcase.py", line 296, in get_testcase_path downloaded_filename = os.listdir(self.testcase_dir_path)[0] 
IndexError: list index out of range
```

Somehow, the testcase isn't cached correctly.

**Comment by tanin47** [comment]
Ok, this is a layout test. When we run it, we move the testcase somewhere else.

A while ago, we added testcase caching #453 which used the folder as the cached record. However, the testcase file was already moved... so there was no testcase file. That's how the bug occurred.

**Comment by tanin47** [comment]
This will eliminate like 1-3% of failures on the CI.
