### ISSUE TITLE
Catch exceptions and print error messages without stacktraces

### ISSUE THREAD

**Issue by Dor1s** [google/clusterfuzz-tools#48]
For example, an attempt to use some unsupported job causes an exception:

```
$ clusterfuzz reproduce 6263517746561024 -b chromium
<...>
Traceback (most recent call last):
  File "/usr/local/bin/clusterfuzz", line 11, in <module>
    sys.exit(execute())
  File "/usr/local/lib/python2.7/dist-packages/clusterfuzz/main.py", line 42, in execute
    command.execute(**arg_dict)
  File "/usr/local/lib/python2.7/dist-packages/clusterfuzz/stackdriver_logging.py", line 89, in wrapped
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/clusterfuzz/commands/reproduce.py", line 231, in execute
    definition = get_binary_definition(current_testcase.job_type, build)
  File "/usr/local/lib/python2.7/dist-packages/clusterfuzz/commands/reproduce.py", line 206, in get_binary_definition
    raise common.JobTypeNotSupportedError(job_type)
clusterfuzz.common.JobTypeNotSupportedError: The job libfuzzer_chrome_asan_debug is not yet supported by clusterfuzz tools.
```

Can we catch it and just print error message without the stacktrace?

**Comment by tanin47** [comment]
I think we can have the `ExpectedException` type where we print the error message without printing the whole stacktrace.
