### ISSUE TITLE
Retrying still doesn't work well

### ISSUE THREAD

**Issue by tanin47** [google/clusterfuzz-tools#511]
```
Detailed log of this run can be found in: /usr/local/google/home/cblume/.clusterfuzz/logs/output.log
Traceback (most recent call last):
  File ".bootstrap/_pex/pex.py", line 328, in execute
  File ".bootstrap/_pex/pex.py", line 260, in _wrap_coverage
  File ".bootstrap/_pex/pex.py", line 292, in _wrap_profiling
  File ".bootstrap/_pex/pex.py", line 371, in _execute
  File ".bootstrap/_pex/pex.py", line 429, in execute_entry
  File ".bootstrap/_pex/pex.py", line 447, in execute_pkg_resources
  File "/usr/local/google/home/cblume/.pex/code/1b8393dcc7ccd3a9ddc5306ed611736509232c4b/clusterfuzz/main.py", line 86, in execute
    command.execute(**arg_dict)
  File "/usr/local/google/home/cblume/.pex/code/1b8393dcc7ccd3a9ddc5306ed611736509232c4b/clusterfuzz/stackdriver_logging.py", line 136, in wrapped
    func(**params)
  File "/usr/local/google/home/cblume/.pex/code/1b8393dcc7ccd3a9ddc5306ed611736509232c4b/clusterfuzz/commands/reproduce.py", line 308, in execute
    reproducer.reproduce(iterations)
  File "/usr/local/google/home/cblume/.pex/code/1b8393dcc7ccd3a9ddc5306ed611736509232c4b/clusterfuzz/reproducers.py", line 462, in reproduce
    return self.reproduce_normal(iteration_max)
  File "/usr/local/google/home/cblume/.pex/code/1b8393dcc7ccd3a9ddc5306ed611736509232c4b/clusterfuzz/reproducers.py", line 408, in reproduce_normal
    new_signature = get_crash_signature(self.job_type, output)
  File "/usr/local/google/home/cblume/.pex/code/1b8393dcc7ccd3a9ddc5306ed611736509232c4b/clusterfuzz/reproducers.py", line 190, in get_crash_signature
    data=json.dumps({'job': job_type, 'stacktrace': raw_stacktrace}))
  File "/usr/local/google/home/cblume/.pex/code/1b8393dcc7ccd3a9ddc5306ed611736509232c4b/clusterfuzz/common.py", line 140, in post
    return get_http().post(*args, **kwargs)
  File "/usr/local/google/home/cblume/.pex/install/requests-2.13.0-py2.py3-none-any.whl.59dc5c6338fb72ca09dcf97dda36a7aaa5d6bd0e/requests-2.13.0-py2.py3-none-any.whl/requests/sessions.py", line 535, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/google/home/cblume/.pex/install/requests_cache-0.4.13-py2.py3-none-any.whl.d4471ee4a3c9d5df1b272c052f2490e8dc3aa3c9/requests_cache-0.4.13-py2.py3-none-any.whl/requests_cache/core.py", line 126, in request
    **kwargs
  File "/usr/local/google/home/cblume/.pex/install/requests-2.13.0-py2.py3-none-any.whl.59dc5c6338fb72ca09dcf97dda36a7aaa5d6bd0e/requests-2.13.0-py2.py3-none-any.whl/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/google/home/cblume/.pex/install/requests_cache-0.4.13-py2.py3-none-any.whl.d4471ee4a3c9d5df1b272c052f2490e8dc3aa3c9/requests_cache-0.4.13-py2.py3-none-any.whl/requests_cache/core.py", line 99, in send
    return send_request_and_cache_response()
  File "/usr/local/google/home/cblume/.pex/install/requests_cache-0.4.13-py2.py3-none-any.whl.d4471ee4a3c9d5df1b272c052f2490e8dc3aa3c9/requests_cache-0.4.13-py2.py3-none-any.whl/requests_cache/core.py", line 91, in send_request_and_cache_response
    response = super(CachedSession, self).send(request, **kwargs)
  File "/usr/local/google/home/cblume/.pex/install/requests-2.13.0-py2.py3-none-any.whl.59dc5c6338fb72ca09dcf97dda36a7aaa5d6bd0e/requests-2.13.0-py2.py3-none-any.whl/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/google/home/cblume/.pex/install/requests-2.13.0-py2.py3-none-any.whl.59dc5c6338fb72ca09dcf97dda36a7aaa5d6bd0e/requests-2.13.0-py2.py3-none-any.whl/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error("(104, 'ECONNRESET')",))
```

**Comment by tanin47** [comment]
This problem might start to happen because of #516.

We have 3 CIs that has been running for a long time. Then, those 3 CIs exhausted all valid testcases. So, they keep pulling for new testcases. For eye-balling it, one CI instance calls ClusterFuzz every second.
